name: Ci-Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        target: 
          - aarch64-linux-android
          - armv7-linux-androideabi
          - x86_64-linux-android
          - i686-linux-android
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - aarch64-pc-windows-gnu
          - x86_64-pc-windows-gnu
        runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: rustup update stable
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }} 
      - name: test
        run: cargo test
